[colors.bright]
black = "0x3e4452"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xe5c07b"

[colors.cursor]
cursor = "0x5c6370"
text = "0x2c323c"

[colors.normal]
black = "0x2c323c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[cursor]
style.shape = "Block"

[font]
size = 12

[font.glyph_offset]
y = 3

[font.normal]
family = "Myrica M"

[font.offset]
y = 4

[terminal.shell]
program = "pwsh"

[window.padding]
x = 3
y = 3

[general]
working_directory = 'C:\Users\NXVZBGBFBEN\'
